tink:
  server:
    deploy: false
  controller:
    deploy: false
rufio:
  deploy: false
hegel:
  deploy: false
smee:
  hostNetwork: true
  publicIP: 192.168.6.127  # Set to the IP address of your node
  trustedProxies:
  - 0.0.0.0/0
  nodeSelector:
    kubernetes.io/hostname: talos-t13-h3c  # Set to the k8s node name. Has to match the publicIP value above
stack:
  enabled: false
